version: "3.7"

services:
  myredis:
    image: redis

  myvotingapp:
    image: paulopez/votingapp
    build:
      dockerfile: Dockerfile
      context: ./src/votingapp
    ports:
      - 8080:5000
    environment:
      REDIS: "myredis:6379"

  mytest:
    image: paulopez/votingapp-test
    build:
      context: ./test
    environment:
      VOTINGAPP_HOST: "myvotingapp:5000"
