version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  redis:
    image: redis

  votingapp:
    image: paulopez/votingapp:${TAG:-latest}-${BASE_IMAGE:-alpine}
    build:
      context: ./src/votingapp
      dockerfile: docker/${BASE_IMAGE:-alpine}/Dockerfile
    environment:
      REDIS: "redis:6379"
    # ports:
    #   - 8080:5000

  test:
    image: paulopez/votingapp-test:${BASE_IMAGE:-alpine}
    build:
      context: ./test/${TEST_TYPE:-shell}
      dockerfile: docker/${BASE_IMAGE:-alpine}/Dockerfile
    environment:
      VOTING_URL: "http://nginx"
      # VOTING_URL: "http://votingapp:5000"
