version: "3.7"

services:
  myredis:
    image: redis

  myvotingapp:
    image: paulopez/votingapp
    build:
      context: ./src/votingapp
      dockerfile: docker/${BASE_IMAGE:-alpine}/Dockerfile
    ports:
      - 8080:5000
    environment:
      REDIS: "myredis:6379"

  mytest:
    image: paulopez/votingapp-test
    build:
      context: ./test/${TEST_TYPE:-shell}
      dockerfile: docker/${BASE_IMAGE:-alpine}/Dockerfile
    environment:
      VOTING_URL: "http://myvotingapp:5000"
